services:
  keycloak:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:latest
    command:
      - "start"
      - "--https-port=8443"
      - "--https-key-store-file=/opt/keycloak/conf/server-keystore.p12"
      - "--https-key-store-password=password"
      - "--https-trust-store-file=/opt/keycloak/conf/server-truststore.p12"
      - "--https-trust-store-password=password"
      - "--hostname=192.168.1.7"
      - "--import-realm"
    ports:
      - 8443:8443
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/myrealm.json
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/myrealm.json:/opt/keycloak/data/import/myrealm.json
      - ./certs/server-keystore.p12:/opt/keycloak/conf/server-keystore.p12
      - ./certs/server-truststore.p12:/opt/keycloak/conf/server-truststore.p12

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - keycloak
    restart: on-failure
    ports:
      - 8082:8082


