spring:
  application:
    name:Keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid+profile+email
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
      resourceserver:
        jwt:
          jwt-set-uri: ${JWT_SET_URI}

server:
  port: 8082
  ssl:
    client-auth: need
    enabled: true

    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: ${TRUST_STORE_PATH}
    trust-store-password: ${TRUST_STORE_PASSWORD}
